### PR TITLE
Site Updates

### PR DESCRIPTION
**Pull request by jacksleight**
I will be pushing all of the updates to this branch and checking things off as they're completed. I will post any task specific notes in comments below.

- [x] Update Statamic to the newest version
- [x] Update footnotes extension to work with Bard/Tiptap 2
- [x] Update converter extension to work with Bard/Tiptap 2
- [x] Implement automatic navgation cache invalidaton when changes are made
- [x] Enable Statamic's Rest API
- [x] Export commentary as PDF
- [x] Implement an index template for top level commentary pages eg. Federal Constitution, link to these from the navigation
- [x] New field type: attachment/additional documents to the commentaries
- [x] Possibility to add links to specific paragraph in the commentaries
- [x] RSS Feed for new commentaries
- [x] Additonal bullet/numbered list styles
- [x] Additional heading level style
- [x] Social media preview image/thumbnail / metatags
- [x] Possibility to add a single quote (') in the suggested citation / legal text
- [x] Possibility to add more than one legal domain to authors and editors
- [x] Sticky navigation button on the website
- [x] New Design for the paragraph numbers in the mobile version of the website
- [x] Links from the author/editor name in the commentaries to the profile page of the author / editor
- [x] Fix link text wrap in DSG 54 (DE)
- [x] Add XML sitemap

### CODE REVIEW

**Comment by jacksleight** [comment]
**Update Statamic to the newest version:**

* `aryehraber/statamic-impersonator` has been removed as impesonate is built-in from v4.23.0
* `format_localized` modifier has been replaced with `iso_format` as per https://statamic.dev/modifiers/format_localized
* Paragraph Number button icon has been updated

**Comment by jacksleight** [comment]
**Update footnotes extension to work with Bard/Tiptap 2:**

* Button icon has been updated to better match the new style

**Comment by jacksleight** [comment]
**Update converter extension to work with Bard/Tiptap 2:**

* These changes are quite involved, all tests are passing and I've tested a couple of sample documents, but it would be a good idea to run a few tests of your own as well

**Comment by jacksleight** [comment]
**Enable Statamic's Rest API:**

* It looks like the API is already enabled for all collections, eg. https://onlinekommentar.ch/api/collections/commentaries/entries/9bf6cc13-cc64-4d0c-967b-ba8bdee8bce8, let me know if you'd like me to enable anything else or adjust these settings

**Comment by jacksleight** [comment]
**Implement automatic navigation cache invalidation when changes are made:**

I've taken a different approach here. The issue with caching the nav is all the open/closed active states stop working, since one copy of the nav is cached from whichever page was loaded first after the cache was cleared. Instead of continuing with that I've remove the caching and just implemented some optimisations instead:

* The `nav` tag now passes the `select` parameter, limiting which entry fields are fetched from the content.
* The `content` check has been changed to `content | raw`, allowing us to check whether there's any content without augmenting it (which adds quite a bit of overhead).

This isn't quite as fast as caching the nav, since we are still generating it, but it's a lot faster than no caching and no optimisations. I think it would be worth testing these changes on production to see how they perform. If we decide it's not fast enough we can look at some smarter per-page caching and automatic invalidation. Or, just enabling the static cache which is probably a good idea anyway.

I've also switched the Antlers parser to runtime, which is now the default and should be faster overall.

**Comment by jacksleight** [comment]
**RSS Feed for new commentaries:**

* There are separate feeds for each site/locale at `/[site]/feed`
* Feeds require the collection to have publish dates enabled, which I've [committed to the data repo](https://github.com/onlinekommentar/onlinekommentar-data/commit/44f332072c4de39550198b03f463dff64d481c9f)

**Comment by jacksleight** [comment]
**Add XML sitemaps:**

* There are separate sitemaps for each site/locale at `/[site]/sitemap.xml`

**Comment by jacksleight** [comment]
**Possibility to add links to specific paragraph in the commentaries**
**New Design for the paragraph numbers in the mobile version of the website**

You can now link to specific paragraphs by appending the paragraph number to the end of the URL eg. `/de/kommentare/bv110#p31`.

I've tweaked the stying of paragraph numbers so they're clearer on mobile:

Screenshot 2023-10-31 at 14 42 05

And also added a highlighted state when you link directly to them (using the method above):

Screenshot 2023-10-31 at 14 41 52

Let me know if you'd like me to adjust any of the stying.

**Comment by jacksleight** [comment]
I've reverted the commentary collection [publish date change](https://github.com/onlinekommentar/onlinekommentar-data/commit/44f332072c4de39550198b03f463dff64d481c9f), as I want to double check that that's definitely necessary. This means the RSS feeds are now blank, but that could be an issue with that addon rather than something we need to change.

**Comment by jacksleight** [comment]
I've re-enabled dates for the commentaries collection. This is not just required for the Feedamic addon, in Statamic v4 dates can't be used at all if they're not switched on (this worked differently in v3), which means the latest commentaries sorting on the home page also doesn't work without this enabled.

**Comment by jacksleight** [comment]
**Additional heading level styles**

* I've enabled level 6 headings in the commentary content and added styling for level 5 and 6 headings.
* I had to change it to use the same sizes on mobile as desktop, as starting at a maximum of `xl` on mobile meant there weren't enough steps to have obviously distinct sizes at the end of the scale.

Screenshot 2023-11-02 at 12 47 40

**Comment by jacksleight** [comment]
**Additional bullet/numbered list styles**

- I've added extra automatic styling for nested bullet and numbered lists.
- If you'd like to be able to choose styles through the CMS I can also add extra list type buttons via my Textstyle addon

Screenshot 2023-11-02 at 13 01 05

**Comment by jacksleight** [comment]
**Possibility to add more than one legal domain to authors and editors**

This has been added, but currently can knock the alignment out a bit. May be worth moving these below the names?

Screenshot 2023-11-02 at 14 31 40

**Comment by jacksleight** [comment]
**Add field for additional documents to commentaries**

* Also requires [this update](https://github.com/onlinekommentar/onlinekommentar-data/commit/e12ea11f710bc9b7da7b0ea37d548030a2447bd8) to the data repo

**Comment by danielbrugger** [comment]
> **Enable Statamic's Rest API:**
> 
> * It looks like the API is already enabled for all collections, eg. https://onlinekommentar.ch/api/collections/commentaries/entries/9bf6cc13-cc64-4d0c-967b-ba8bdee8bce8, let me know if you'd like me to enable anything else or adjust these settings

**Comment by danielbrugger** [comment]
It would be great if you could add a central page where people can access the API.

**Comment by danielbrugger** [comment]
> I've reverted the commentary collection [publish date change](https://github.com/onlinekommentar/onlinekommentar-data/commit/44f332072c4de39550198b03f463dff64d481c9f), as I want to double check that that's definitely necessary. This means the RSS feeds are now blank, but that could be an issue with that addon rather than something we need to change.



> **Additional heading level styles**
> 
> * I've enabled level 6 headings in the commentary content and added styling for level 5 and 6 headings.
> * I had to change it to use the same sizes on mobile as desktop, as starting at a maximum of `xl` on mobile meant there weren't enough steps to have obviously distinct sizes at the end of the scale.
> 
> Screenshot 2023-11-02 at 12 47 40



> I've reverted the commentary collection [publish date change](https://github.com/onlinekommentar/onlinekommentar-data/commit/44f332072c4de39550198b03f463dff64d481c9f), as I want to double check that that's definitely necessary. This means the RSS feeds are now blank, but that could be an issue with that addon rather than something we need to change.


> **Additional heading level styles**
> 
> * I've enabled level 6 headings in the commentary content and added styling for level 5 and 6 headings.
> * I had to change it to use the same sizes on mobile as desktop, as starting at a maximum of `xl` on mobile meant there weren't enough steps to have obviously distinct sizes at the end of the scale.
> 
> Screenshot 2023-11-02 at 12 47 40

Heading 6 in all caps (HEADING), I would change it to normal style (Heading). The text size of heading 5 in the current version is now smaller than the normal font size for text (e.g. https://onlinekommentar.ch/de/kommentare/bv75b paragraph 9; the heading text unmittelbare Anwendbarkeit is smaller than the text). Should be adjusted so that headings are at least the same size as normal text.

**Comment by danielbrugger** [comment]
you m

> I've reverted the commentary collection [publish date change](https://github.com/onlinekommentar/onlinekommentar-data/commit/44f332072c4de39550198b03f463dff64d481c9f), as I want to double check that that's definitely necessary. This means the RSS feeds are now blank, but that could be an issue with that addon rather than something we need to change.

Not sure if I understand it correctly, but for the project it is important that the published date remains the same. For example the publication date of Art. 5 BV https://onlinekommentar.ch/de/kommentare/bv5a needs to stay at 17.01.2023 14:26:54 CET

**Comment by jacksleight** [comment]
**Export commentary as PDF**

* Due to the footnotes requirement we can't use any of the usual HTML to PDF conversion tools, since HTML has no concept of footnotes. Therefore to achieve this the simplest method is to take the existing Word document generation and then convert that to PDF. The best tool I've found for this is [Gotenburg (using LibreOffice)](https://gotenberg.dev/), which is distributed as a Docker image so should hopefully be straightforward to get set up on the live server.

**Comment by jacksleight** [comment]
> Not sure if I understand it correctly, but for the project it is important that the published date remains the same. For example the publication date of Art. 5 BV [onlinekommentar.ch/de/kommentare/bv5a](https://onlinekommentar.ch/de/kommentare/bv5a) needs to stay at 17.01.2023 14:26:54 CET

Yep that's fine, I've since reverted the reversion.

On the current live site dates aren't actually enabled (explicitly), but Statamic v3 allows you to use the dates even if the config option isn't enabled. With the upgrade to v4 the dates stopped working, as v4 requires the option to be enabled.

I originally enabled it, but then decided I wanted to double-check that was definitely necessary so reverted it, and then confirmed that it was so re-enabled it again. 🙂

**Comment by jacksleight** [comment]
@danielbrugger @schwemmer I've just pushed the latest changes following our review earlier this week. These updates are now ready for final review/testing and deployment.

**Comment by jacksleight** [comment]
Just pushed the latest updates after feedback from @schwemmer:

- [x] Now using antlers `trans` tags rather than PHP tags wherever possible
- [x] Navigation caching has been reimplemented with a custom tag that supports current/parent page states correctly, and on entry updates the cached navigations will be cleared
- [x] Commentary titles in the grid now clamped to 3 lines instead of 4
- [x] Paragraph number bubbles now aligned to edge of text
- [x] Missing filters on authors and editors pages fixed
- [x] Replaced `sys_get_temp_dir` with `storage_path` to fix temporary file issue on Docker
- [x] Additional documents and PDF download labels now use translation strings (translations for de, fr, and it are needed)

I tried to upgrade the site to latest v4 (4.37.0) but started getting infinite recursion errors on the commentary show pages. I suspect there's a bug in the latest release but need to investigate. Have reverted to 4.32.0 for now.

I have also created an FR on the Feedamic addon that will allow us to filter out the legal domain pages from the commentaries feed. I'll see what they think and work on a PR if they like the idea.

**Pull request merged**
